server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# h2
spring:
  datasource:
    url: jdbc:h2:mem:kpsecdb;MODE=Oracle
    platform: h2
    username: kpsec
    password: kpsec
    driverClassName: org.h2.Driver
    #data: classpath:db/h2/data.sql # spring boot startup 시, 특정 경로의 data.sql 실행


  h2:
    console:
      enabled: true
      path: /h2-console

  # jpa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  
  #devtool      
  devtools:
    livereload:
      enabled: true